# Generated by Django 3.0.6 on 2020-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tempCollegeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remail', models.EmailField(default='', max_length=50)),
                ('ccbcc', models.EmailField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(default='', max_length=50)),
                ('department', models.CharField(default='', max_length=50)),
                ('cname', models.CharField(default='', max_length=50)),
                ('cno', models.IntegerField()),
            ],
        ),
    ]
