# Generated by Django 2.2.12 on 2020-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
