# Generated by Django 2.2.12 on 2020-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='editMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(default='', max_length=50)),
                ('ccbcc', models.EmailField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('body', models.CharField(default='', max_length=500)),
                ('attachments', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
