# Generated by Django 3.0.6 on 2020-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tempcollegedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcollegedata',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
