# Generated by Django 3.0.6 on 2020-05-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tempcollegedata_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collegeData',
            new_name='clgData',
        ),
    ]
