# Generated by Django 2.2.12 on 2020-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_elsicollegedtls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElsiTeacherDtls',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('clg_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('emailid', models.TextField(blank=True, null=True)),
                ('alt_email1', models.TextField(blank=True, null=True)),
                ('alt_email2', models.TextField(blank=True, null=True)),
                ('contact_num', models.TextField(blank=True, null=True)),
                ('alt_contact1', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('coor_flag', models.IntegerField(blank=True, null=True)),
                ('wo_flag', models.IntegerField(blank=True, null=True)),
                ('workshop_id', models.IntegerField(blank=True, null=True)),
                ('wo_attendee', models.IntegerField(blank=True, null=True)),
                ('wo_count', models.IntegerField(blank=True, null=True)),
                ('eyrtc_flag', models.IntegerField(blank=True, null=True)),
                ('tbt_flag', models.IntegerField(blank=True, null=True)),
                ('eyic_flag', models.TextField(blank=True, null=True)),
                ('content_flag', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('status_flag', models.TextField(blank=True, null=True)),
                ('modified_by', models.TextField(blank=True, null=True)),
                ('elsi_flag', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('login_created', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elsi_teacher_dtls',
                'managed': False,
            },
        ),
    ]
