# Generated by Django 3.0.6 on 2020-06-04 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locstate', models.CharField(default='', max_length=50)),
                ('locdistrict', models.CharField(default='', max_length=50)),
                ('locemail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
