# Generated by Django 3.0.6 on 2020-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopTeamDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('workshop_id', models.TextField()),
                ('options', models.CharField(max_length=50)),
                ('category_eyic', models.CharField(default='None', max_length=50)),
                ('category_eyrc', models.CharField(default='None', max_length=50)),
                ('category_eyrdc', models.CharField(default='None', max_length=50)),
                ('category_elsi', models.CharField(default='None', max_length=50)),
                ('category_web', models.CharField(default='None', max_length=50)),
                ('category_others', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='locData',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
