# Generated by Django 2.2.12 on 2020-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopstakencount',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
