# Generated by Django 2.2.12 on 2020-06-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetail',
            table='userdetail',
        ),
    ]
