# Generated by Django 3.0.7 on 2020-06-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_workshop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='demodtls',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='headdetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workshopstakencount',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workshopteamstatus',
            options={'managed': False},
        ),
    ]
