# Generated by Django 2.2.12 on 2020-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='language',
            field=models.TextField(default='0', null=True),
        ),
    ]
