# Generated by Django 2.2.12 on 2020-06-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workshopteamdtls',
            table='workshop_team_dtls',
        ),
    ]
