# Generated by Django 2.2.12 on 2020-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_editmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='locData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locstate', models.CharField(default='', max_length=50)),
                ('locdistrict', models.CharField(default='', max_length=50)),
                ('locemail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='editMail',
        ),
    ]
