# Generated by Django 2.2.12 on 2020-06-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200612_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'managed': False},
        ),
    ]
