# Generated by Django 2.2.12 on 2020-06-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200612_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={},
        ),
    ]
