# Generated by Django 2.2.12 on 2020-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200612_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
