# Generated by Django 2.2.12 on 2020-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200612_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='course_or_other_eyantra_work',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='eLSI',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='eYIC',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='eYRC',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='eYRDC',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='personal_or_any_other',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='web',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopteamstatus',
            name='willingness_or_unavailability',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
