# Generated by Django 2.2.12 on 2020-06-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_workshopdtls_workshopparticipants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clgData',
        ),
    ]
