# Generated by Django 2.2.12 on 2020-06-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_clgdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICTE_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.TextField()),
                ('state', models.TextField()),
                ('district', models.TextField()),
                ('city', models.TextField()),
                ('full_address', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
            options={
                'db_table': 'aicte_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='locData',
        ),
    ]
